### ISSUE TITLE
ipv6 error

### ISSUE THREAD

**Issue by marcio4tap** [LouisBrunner/avahi2dns#2]
Hello!

Thank you for your program, it served perfectly what I needed.

I'm using both IPv4 and IPv6 and I got an error resolving names to IPv6. I didn't quite understand how the call to Avahi should be, however, changing from avahi.ProtoUnspec to the chosen protocol worked correctly.

https://github.com/LouisBrunner/avahi2dns/blob/44c5b8f047a15c10b40fc888df15ce5abef5ef0a/query.go#L53

**Comment by LouisBrunner** [comment]
Hi @marcio4tap!

Thanks for raising this issue.

Do you mean using something like `aserver.ResolveHostName(avahi.InterfaceUnspec, proto, name, proto, 0)`?

I had a look through Avahi's codebase and I am not entirely sure what the difference is between both protocol but if it works for you, I am happy to give it a try. 😄

**Comment by LouisBrunner** [comment]
Released as `0.0.2`
